"Health Insurance Marketplace"
 Explore health and dental plans data in the US Health Insurance Marketplace

1️⃣ : Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

2️⃣ : Reading The Dataset

In [11]:
Benifit_cost=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\project\BenefitsCostSharing.csv")

C:\Users\hp\AppData\Local\Temp\ipykernel_14848\3598376911.py:1: DtypeWarning: Columns (3,6,9,10,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  Benifit_cost=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\project\BenefitsCostSharing.csv")


In [14]:
Benifit_cost

BenefitName  BusinessYear  \
0        Routine Dental Services (Adult)          2014   
1           Dental Check-Up for Children          2014   
2              Basic Dental Care - Child          2014   
3                    Orthodontia - Child          2014   
4              Major Dental Care - Child          2014   
...                                  ...           ...   
5048403        Major Dental Care - Child          2016   
5048404        Basic Dental Care - Adult          2016   
5048405              Orthodontia - Adult          2016   
5048406        Major Dental Care - Adult          2016   
5048407                Accidental Dental          2016   

                            CoinsInnTier1 CoinsInnTier2  \
0                                     20%           NaN   
1                                     20%           NaN   
2                                     40%           NaN   
3                                     50%           NaN   
4                                     50%           NaN   
...                                   ...           ...   
5048403  50% Coinsurance after deductible           NaN   
5048404                               NaN           NaN   
5048405                               NaN           NaN   
5048406                               NaN           NaN   
5048407                               NaN           NaN   

                            CoinsOutofNet   CopayInnTier1 CopayInnTier2  \
0                                     20%       No Charge           NaN   
1                                     20%       No Charge           NaN   
2                                     40%       No Charge           NaN   
3                                     50%       No Charge           NaN   
4                                     50%       No Charge           NaN   
...                                   ...             ...           ...   
5048403  50% Coinsurance after deductible  Not Applicable           NaN   
5048404                               NaN             NaN           NaN   
5048405                               NaN             NaN           NaN   
5048406                               NaN             NaN           NaN   
5048407                               NaN             NaN           NaN   

          CopayOutofNet            EHBVarReason Exclusions  ...  \
0             No Charge               Above EHB        NaN  ...   
1             No Charge     Substantially Equal        NaN  ...   
2             No Charge     Substantially Equal        NaN  ...   
3             No Charge  Additional EHB Benefit        NaN  ...   
4             No Charge     Substantially Equal        NaN  ...   
...                 ...                     ...        ...  ...   
5048403  Not Applicable                     NaN        NaN  ...   
5048404             NaN                     NaN        NaN  ...   
5048405             NaN                     NaN        NaN  ...   
5048406             NaN                     NaN        NaN  ...   
5048407             NaN                     NaN        NaN  ...   

                     LimitUnit MinimumStay             PlanId QuantLimitOnSvc  \
0             Dollars per Year         NaN  21989AK0010001-00             Yes   
1        Visit(s) per 6 Months         NaN  21989AK0010001-00             Yes   
2                          NaN         NaN  21989AK0010001-00             NaN   
3                          NaN         NaN  21989AK0010001-00             NaN   
4                          NaN         NaN  21989AK0010001-00             NaN   
...                        ...         ...                ...             ...   
5048403                    NaN         NaN  96480WV0110003-00             NaN   
5048404                    NaN         NaN  96480WV0110003-00             NaN   
5048405                    NaN         NaN  96480WV0110003-00             NaN   
5048406                    NaN         NaN  96480WV0110003-00             NaN   
5048407                   

3️⃣ : Dataset Overview

In [ ]:
★ Benefit cost dataset have  has 32 Columns and 5048408 Rows.

In [19]:
Benifit_cost.shape # Here wwe are find out the columns and rows

(5048408, 32)

In [23]:
Benifit_cost.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5048408 entries, 0 to 5048407
Data columns (total 32 columns):
 #   Column               Dtype  
---  ------               -----  
 0   BenefitName          object 
 1   BusinessYear         int64  
 2   CoinsInnTier1        object 
 3   CoinsInnTier2        object 
 4   CoinsOutofNet        object 
 5   CopayInnTier1        object 
 6   CopayInnTier2        object 
 7   CopayOutofNet        object 
 8   EHBVarReason         object 
 9   Exclusions           object 
 10  Explanation          object 
 11  ImportDate           object 
 12  IsCovered            object 
 13  IsEHB                object 
 14  IsExclFromInnMOOP    object 
 15  IsExclFromOonMOOP    object 
 16  IsStateMandate       object 
 17  IsSubjToDedTier1     object 
 18  IsSubjToDedTier2     object 
 19  IssuerId             int64  
 20  IssuerId2            int64  
 21  LimitQty             float64
 22  LimitUnit            object 
 23  MinimumStay          float64
 24

In [29]:
Benifit_cost.head(5)

BenefitName  BusinessYear CoinsInnTier1 CoinsInnTier2  \
0  Routine Dental Services (Adult)          2014           20%           NaN   
1     Dental Check-Up for Children          2014           20%           NaN   
2        Basic Dental Care - Child          2014           40%           NaN   
3              Orthodontia - Child          2014           50%           NaN   
4        Major Dental Care - Child          2014           50%           NaN   

  CoinsOutofNet CopayInnTier1 CopayInnTier2 CopayOutofNet  \
0           20%     No Charge           NaN     No Charge   
1           20%     No Charge           NaN     No Charge   
2           40%     No Charge           NaN     No Charge   
3           50%     No Charge           NaN     No Charge   
4           50%     No Charge           NaN     No Charge   

             EHBVarReason Exclusions  ...              LimitUnit MinimumStay  \
0               Above EHB        NaN  ...       Dollars per Year         NaN   
1     Substantially Equal        NaN  ...  Visit(s) per 6 Months         NaN   
2     Substantially Equal        NaN  ...                    NaN         NaN   
3  Additional EHB Benefit        NaN  ...                    NaN         NaN   
4     Substantially Equal        NaN  ...                    NaN         NaN   

              PlanId QuantLimitOnSvc RowNumber SourceName StandardComponentId  \
0  21989AK0010001-00             Yes        68       HIOS      21989AK0010001   
1  21989AK0010001-00             Yes       104       HIOS      21989AK0010001   
2  21989AK0010001-00             NaN       110       HIOS      21989AK0010001   
3  21989AK0010001-00             NaN       111       HIOS      21989AK0010001   
4  21989AK0010001-00             NaN       112       HIOS      21989AK0010001   

  StateCode StateCode2  VersionNum  
0        AK         AK           6  
1        AK         AK           6  
2        AK         AK           6  
3        AK         AK           6  
4        AK         AK           6  

[5 rows x 32 columns]

In [33]:
Benifit_cost.tail(5)

BenefitName  BusinessYear  \
5048403  Major Dental Care - Child          2016   
5048404  Basic Dental Care - Adult          2016   
5048405        Orthodontia - Adult          2016   
5048406  Major Dental Care - Adult          2016   
5048407          Accidental Dental          2016   

                            CoinsInnTier1 CoinsInnTier2  \
5048403  50% Coinsurance after deductible           NaN   
5048404                               NaN           NaN   
5048405                               NaN           NaN   
5048406                               NaN           NaN   
5048407                               NaN           NaN   

                            CoinsOutofNet   CopayInnTier1 CopayInnTier2  \
5048403  50% Coinsurance after deductible  Not Applicable           NaN   
5048404                               NaN             NaN           NaN   
5048405                               NaN             NaN           NaN   
5048406                               NaN             NaN           NaN   
5048407                               NaN             NaN           NaN   

          CopayOutofNet EHBVarReason Exclusions  ... LimitUnit MinimumStay  \
5048403  Not Applicable          NaN        NaN  ...       NaN         NaN   
5048404             NaN          NaN        NaN  ...       NaN         NaN   
5048405             NaN          NaN        NaN  ...       NaN         NaN   
5048406             NaN          NaN        NaN  ...       NaN         NaN   
5048407             NaN          NaN        NaN  ...       NaN         NaN   

                    PlanId QuantLimitOnSvc RowNumber SourceName  \
5048403  96480WV0110003-00             NaN       112      SERFF   
5048404  96480WV0110003-00             NaN       113      SERFF   
5048405  96480WV0110003-00             NaN       114      SERFF   
5048406  96480WV0110003-00             NaN       115      SERFF   
5048407  96480WV0110003-00             NaN       118      SERFF   

        StandardComponentId StateCode StateCode2  VersionNum  
5048403      96480WV0110003        WV         WV           2  
5048404      96480WV0110003        WV         WV           2  
5048405      96480WV0110003        WV         WV           2  
5048406      96480WV0110003        WV         WV           2  
5048407      96480WV0110003        WV         WV           2  

[5 rows x 32 columns]

In [35]:
Benifit_cost.describe()

BusinessYear      IssuerId     IssuerId2       LimitQty   MinimumStay  \
count  5.048408e+06  5.048408e+06  5.048408e+06  687683.000000  16727.000000   
mean   2.015127e+03  5.220360e+04  5.220360e+04     142.399374     47.937048   
std    7.563664e-01  2.592498e+04  2.592498e+04    1723.372817      5.892297   
min    2.014000e+03  1.004600e+04  1.004600e+04       1.000000      5.000000   
25%    2.015000e+03  3.253600e+04  3.253600e+04       1.000000     48.000000   
50%    2.015000e+03  4.839600e+04  4.839600e+04      20.000000     48.000000   
75%    2.016000e+03  7.498000e+04  7.498000e+04      40.000000     48.000000   
max    2.016000e+03  9.996900e+04  9.996900e+04   75000.000000     90.000000   

          RowNumber    VersionNum  
count  5.048408e+06  5.048408e+06  
mean   9.839018e+01  7.637094e+00  
std    2.177890e+01  3.803627e+00  
min    6.100000e+01  1.000000e+00  
25%    8.000000e+01  5.000000e+00  
50%    9.900000e+01  7.000000e+00  
75%    1.170000e+02  9.000000e+00  
max    1.560000e+02  2.400000e+01

In [37]:
Benifit_cost.describe(include=object)

BenefitName                     CoinsInnTier1   CoinsInnTier2  \
count               5048408                           3934561          476821   
unique                  861                               115              37   
top     Orthodontia - Adult  20% Coinsurance after deductible  Not Applicable   
freq                  77377                            673204          185524   

       CoinsOutofNet CopayInnTier1   CopayInnTier2 CopayOutofNet  \
count        3934561       3934561          476821       3934559   
unique            60           516             278           232   
top             100%     No Charge  Not Applicable     No Charge   
freq         1864875       1534500          199578       1371646   

               EHBVarReason  \
count               2027671   
unique                   12   
top     Substantially Equal   
freq                 776295   

                                               Exclusions  \
count                                              476161   
unique                                               1720   
top     Member cost share based on place and type of s...   
freq                                                31531   

                                              Explanation  ... IsStateMandate  \
count                                              972708  ...         797945   
unique                                               6227  ...              1   
top     Quantitative limit units apply, see EHB benchm...  ...            Yes   
freq                                                21571  ...         797945   

       IsSubjToDedTier1 IsSubjToDedTier2          LimitUnit  \
count           2582531          2582354             687869   
unique                5                4                 88   
top                 Yes              Yes  Visit(s) per Year   
freq            1945742          1313161             308545   

                   PlanId QuantLimitOnSvc SourceName StandardComponentId  \
count             5048408         1783876    5048408             5048408   
unique              52394               5          3               16807   
top     31274WV0310001-03              No       HIOS      58288IL0380016   
freq                  291         1106768    3049221                1848   

       StateCode StateCode2  
count    5048408    5048408  
unique        39         39  
top           WI         WI  
freq      512587     512587  

[4 rows x 25 columns]

5️⃣ Analysing Sum of Duplicated Data in Benefit cost shring Dataset

In [42]:
Benifit_cost.duplicated().sum()

86

6️⃣ Detecting Sum of Empty Cells with no value in HealthCare Dataset

In [47]:
Benifit_cost.isnull().sum()

BenefitName                  0
BusinessYear                 0
CoinsInnTier1          1113847
CoinsInnTier2          4571587
CoinsOutofNet          1113847
CopayInnTier1          1113847
CopayInnTier2          4571587
CopayOutofNet          1113849
EHBVarReason           3020737
Exclusions             4572247
Explanation            4075700
ImportDate                   0
IsCovered               215980
IsEHB                  1817362
IsExclFromInnMOOP       983986
IsExclFromOonMOOP       982626
IsStateMandate         4250463
IsSubjToDedTier1       2465877
IsSubjToDedTier2       2466054
IssuerId                     0
IssuerId2                    0
LimitQty               4360725
LimitUnit              4360539
MinimumStay            5031681
PlanId                       0
QuantLimitOnSvc        3264532
RowNumber                    0
SourceName                   0
StandardComponentId          0
StateCode                    0
StateCode2                   0
VersionNum                   0
dtype: i

In [ ]:
## Here most of columns showing empty and missig value some times values are in str becuse of that

7️⃣ Finding Unique values in HealthCare Dataset
7.1 Number of Unique value per Column

In [53]:
Benifit_cost.nunique()

BenefitName              861
BusinessYear               3
CoinsInnTier1            115
CoinsInnTier2             37
CoinsOutofNet             60
CopayInnTier1            516
CopayInnTier2            278
CopayOutofNet            232
EHBVarReason              12
Exclusions              1720
Explanation             6227
ImportDate               266
IsCovered                  3
IsEHB                      1
IsExclFromInnMOOP          5
IsExclFromOonMOOP          4
IsStateMandate             1
IsSubjToDedTier1           5
IsSubjToDedTier2           4
IssuerId                 910
IssuerId2                910
LimitQty                  94
LimitUnit                 88
MinimumStay                3
PlanId                 52394
QuantLimitOnSvc            5
RowNumber                 96
SourceName                 3
StandardComponentId    16807
StateCode                 39
StateCode2                39
VersionNum                23
dtype: int64

7.2 Unique value per Column

In [57]:
Benifit_cost['BenefitName'].unique()

array(['Routine Dental Services (Adult)', 'Dental Check-Up for Children',
       'Basic Dental Care - Child', 'Orthodontia - Child',
       'Major Dental Care - Child', 'Basic Dental Care - Adult',
       'Orthodontia - Adult', 'Major Dental Care - Adult',
       'Accidental Dental', 'Non-Medically Necessary Orthodontia',
       'Inpatient Hospital Services (e.g., Hospital Stay)',
       'Inpatient Physician and Surgical Services', 'Bariatric Surgery',
       'Cosmetic Surgery', 'Skilled Nursing Facility',
       'Prenatal and Postnatal Care',
       'Delivery and All Inpatient Services for Maternity Care',
       'Mental/Behavioral Health Outpatient Services',
       'Mental/Behavioral Health Inpatient Services',
       'Substance Abuse Disorder Outpatient Services',
       'Non-Medically Necessary Orthodontia - Child',
       'Primary Care Visit to Treat an Injury or Illness',
       'Specialist Visit',
       'Other Practitioner Office Visit (Nurse, Physician Assistant)',
       'Ou

In [59]:
Benifit_cost['BusinessYear'].unique() 

array([2014, 2015, 2016], dtype=int64)

In [61]:
Benifit_cost['CoinsInnTier1'].unique()

array(['20%', '40%', '50%', nan, '0%', '30%',
       '50% Coinsurance after deductible',
       '100% Coinsurance after deductible',
       '80% Coinsurance after deductible', 'No Charge',
       '20% Coinsurance after deductible',
       '40% Coinsurance after deductible',
       '30% Coinsurance after deductible',
       '60% Coinsurance after deductible', 'No Charge after deductible',
       '45% Coinsurance after deductible',
       '65% Coinsurance after deductible', '100%', '15%', '45%', '35%',
       '0% Coinsurance after deductible',
       '70% Coinsurance after deductible',
       '10% Coinsurance after deductible', '10%',
       '35% Coinsurance after deductible',
       '15% Coinsurance after deductible',
       '5% Coinsurance after deductible', '$0', '25%', '65%',
       '25% Coinsurance after deductible', '5%', '60%', '13%', '18%',
       '18% Coinsurance after deductible', '21%', '55%',
       '55% Coinsurance after deductible',
       '16% Coinsurance after deductible'

In [63]:
Benifit_cost['CoinsInnTier2'].unique()

array([nan, '0%', '20% Coinsurance after deductible', 'No Charge',
       '50% Coinsurance after deductible',
       '0% Coinsurance after deductible', '20%',
       '10% Coinsurance after deductible', '10%', '30%', '40%', '50%',
       '40% Coinsurance after deductible', 'No Charge after deductible',
       '25% Coinsurance after deductible', '25%',
       '35% Coinsurance after deductible',
       '30% Coinsurance after deductible', '$0', '100%',
       '9% Coinsurance after deductible',
       '19% Coinsurance after deductible',
       '29% Coinsurance after deductible',
       '60% Coinsurance after deductible', '35%',
       '5% Coinsurance after deductible', '49%', '8%',
       '70% Coinsurance after deductible',
       '75% Coinsurance after deductible',
       '45% Coinsurance after deductible',
       '80% Coinsurance after deductible',
       '15% Coinsurance after deductible', '60%', '15%', 'Not Applicable',
       '100% Coinsurance after deductible',
       '55% Coinsurance

In [83]:
Benifit_cost['CoinsOutofNet'].unique()              

array(['20%', '40%', '50%', nan, '0%', '30%',
       '50% Coinsurance after deductible',
       '100% Coinsurance after deductible',
       '80% Coinsurance after deductible', 'No Charge',
       '20% Coinsurance after deductible',
       '40% Coinsurance after deductible',
       '30% Coinsurance after deductible',
       '60% Coinsurance after deductible', 'No Charge after deductible',
       '45% Coinsurance after deductible',
       '65% Coinsurance after deductible', '100%',
       '10% Coinsurance after deductible', '15%', '45%', '35%', '80%',
       '70% Coinsurance after deductible',
       '25% Coinsurance after deductible', '10%',
       '0% Coinsurance after deductible',
       '90% Coinsurance after deductible',
       '15% Coinsurance after deductible',
       '5% Coinsurance after deductible', '70%', '$0', '5%', '60%',
       '55% Coinsurance after deductible',
       '35% Coinsurance after deductible',
       '75% Coinsurance after deductible',
       '85% Coinsurance af

In [81]:
Benifit_cost['CopayInnTier1'].unique()          

array(['No Charge', nan, '$0 Copay per Day', '$45', '$15', '$10', '$0',
       '$25', '$30', '$35', '$50', '$60', '$35 Copay before deductible',
       '$35 Copay after deductible', '$17', '$50 Copay after deductible',
       '$8', '$20 Copay after deductible', '$20', '$150',
       '$150 Copay per Day', '$100', '$200', '$200 Copay per Day', '$40',
       '$300 Copay per Day', '$55', '$395', '$300', '$75',
       '$75 Copay per Day', '$5', '$0 Copay per Stay', '$70', '$80',
       '$65', '$500', '$10 Copay after deductible',
       '$70 Copay after deductible', '$350', '$500 Copay per Stay',
       '$0 Copay after deductible', '$1,000',
       '$60 Copay after deductible', 'No Charge after deductible', '$750',
       '$125', '$1000 Copay per Day', '$1000', '$85',
       '$250 Copay before deductible', '$15 Copay after deductible',
       '$40 Copay after deductible', '$250',
       '$10 Copay before deductible', '$3', '$90', '$160', '$120', '$95',
       '$110', '$180', '$1,500', '$500

In [79]:
Benifit_cost['CopayInnTier2'].unique()                             

array([nan, '$100', '$0', '$200', 'No Charge', '$400', '$35', '$50',
       '$15', '$400 Copay per Day', '$40', '$60', '$0 Copay per Day',
       '$65', '$20', '$395', '$600', '$25', '$300', '$600 Copay per Day',
       '$30', '$75', '$10', '$5', '$750', '$25 Copay after deductible',
       '$500', 'No Charge after deductible', '$50 Copay after deductible',
       '$500 Copay per Day', '$1,000', '$500 Copay after deductible',
       '$400 Copay after deductible', '$300 Copay after deductible',
       '$1000 Copay after deductible', '$100 Copay after deductible',
       '$60 Copay after deductible', '$200 Copay after deductible',
       '$75 Copay after deductible', '$1250 Copay after deductible',
       '$40 Copay after deductible', '$150', '$200 Copay per Day', '$320',
       '$80', '$20 Copay after deductible', '$100 Copay per Day',
       '$50 Copay per Day', '$120', '$750 Copay before deductible',
       '$150 Copay before deductible', '$500 Copay before deductible',
       '$200 C

In [77]:
Benifit_cost['CopayOutofNet'].unique()

array(['No Charge', nan, '$0 Copay per Day', '$10', '$0', '$15', '$35',
       '$50', '$150 Copay after deductible', '$300 Copay per Stay',
       '$200 Copay after deductible', '$800 Copay per Stay', '$800',
       '$300 Copay after deductible', '$1200 Copay per Stay',
       '$75 Copay after deductible', '$0 Copay per Stay', '$20', '$65',
       '$100', '$10 Copay after deductible', '$35 Copay after deductible',
       '$70 Copay after deductible', '$60', '$70', '$200',
       '$60 Copay after deductible', 'No Charge after deductible', '$500',
       '$45', '$85', '$350', '$250', '$250 Copay after deductible',
       '$300', '$1,000', '$40', '$80', '$25', '$750', '$5', '$30', '$90',
       '$75', '$150', '$160', '$120', '$55', '$95', '$110', '$180',
       '$1,500', '$125', '$1,250', '$40 Copay after deductible',
       '$15 Copay after deductible', '$100 Copay after deductible',
       '$55 Copay after deductible', '$500 Copay per Stay',
       '$500 Copay after deductible', '$8', '

In [75]:
Benifit_cost['EHBVarReason'].unique()              

array(['Above EHB', 'Substantially Equal', 'Additional EHB Benefit', nan,
       'Dental Only Plan Available', 'Other Law/Regulation',
       'Substituted', 'Above Ehb', 'above EHB',
       'Using Alternate Benchmark', 'additional EHB Benefit',
       '\nAdditional EHB Benefit', 'Substantially equal'], dtype=object)

In [85]:
Benifit_cost['Exclusions'].unique()               

array([nan,
       'Damage resulting from chewing or biting food or other objects',
       'Excludes Assistive Reproductive Technology,  ART; i.e invitro, GIFT, ZIFT (refer to CDC website for definition of ART)',
       ...,
       'Out of Network mail order pharmacy services and Out of Network Specialty drugs are not covered',
       'Artificial Insemination, In Vitro Fertilization and Drugs not covered.',
       'Excludes Artificial Insemination (AI), In Vitro Fertilization (IVF) and Drugs.'],
      dtype=object)

In [87]:
Benifit_cost['Explanation'].unique()             

array(['Combined annual benefit maximum of $1000 per year for adults. See policy for additional limitations',
       'See policy for additional limitations',
       '24 month waiting period, See policy for additional limitations',
       ...,
       'Coverage is limited to 30 visits. Benefit limits are shared between rehabilitation and habilitation services.',
       'Coverage is limited to 30 visits PT/OT combined. Benefit limits are shared between rehabilitation and habilitation services.',
       'Medically Necessary Only - 12 Month Wait'], dtype=object)

In [89]:
Benifit_cost['ImportDate'].unique()                

array(['2014-03-19 07:06:49', '2013-08-01 12:48:00',
       '2014-04-18 11:49:29', '2013-09-02 11:39:25',
       '2013-06-04 08:25:28', '2014-01-21 08:29:49',
       '2013-06-06 10:50:48', '2014-01-17 09:36:20',
       '2013-09-10 14:43:20', '2014-01-16 07:24:04',
       '2013-10-15 07:27:56', '2013-09-17 16:07:07',
       '2013-09-16 06:33:22', '2013-07-01 08:34:30',
       '2013-11-23 14:44:18', '2013-09-12 11:27:35',
       '2013-11-26 13:14:08', '2013-09-19 06:29:55',
       '2013-08-30 07:44:10', '2013-10-16 16:52:58',
       '2014-05-02 13:10:05', '2013-06-28 08:36:25',
       '2013-07-23 22:50:01', '2013-07-31 07:05:07',
       '2014-01-15 07:08:32', '2013-06-05 12:49:14',
       '2013-09-13 08:31:59', '2013-07-01 22:22:31',
       '2013-09-11 07:49:18', '2014-01-29 08:00:05',
       '2013-06-07 09:05:04', '2013-09-25 08:49:23',
       '2013-07-02 22:25:47', '2014-07-25 16:54:18',
       '2013-09-05 07:36:38', '2013-12-20 07:30:10',
       '2013-08-09 08:21:29', '2014-01-22 07:3

In [91]:
Benifit_cost['IsCovered'].unique()                   

array(['Covered', nan, 'Not Covered', 'Not covered'], dtype=object)

In [93]:
Benifit_cost['IsEHB'].unique()                       

array([nan, 'Yes'], dtype=object)

In [101]:
Benifit_cost['IsExclFromInnMOOP'].unique()               

array(['No', nan, 'Yes', 'NO', 'no', 'yes'], dtype=object)

In [102]:
Benifit_cost['IsStateMandate'].unique()    

array([nan, 'Yes'], dtype=object)

In [105]:
Benifit_cost['IsSubjToDedTier1'].unique()

array(['No', 'Yes', nan, 'YES', 'no', 'yes'], dtype=object)

In [106]:
Benifit_cost['IsSubjToDedTier2'].unique()

array(['No', 'Yes', nan, 'no', 'NO'], dtype=object)

In [108]:
Benifit_cost['IssuerId'].unique()

array([21989, 38536, 73836, 42507, 45858, 74819, 84859, 12538, 44580,
       17540, 46944, 44785, 46211, 59809, 77233, 82285, 23307, 17100,
       17454, 18156, 51485, 30045, 33851, 52147, 53901, 58292, 60761,
       70239, 66105, 77352, 84251, 86830, 88925, 91450, 90264, 92045,
       99180, 15833, 15980, 16842, 23841, 27357, 30252, 30115, 30219,
       35783, 48121, 43274, 49193, 51398, 48129, 54172, 56503, 57451,
       77150, 59667, 85543, 86382, 97725, 98534, 99787, 45495, 28167,
       37001, 49046, 50988, 55612, 73231, 50491, 50662, 63411, 63940,
       83502, 83761, 86637, 89942, 93332, 17575, 35065, 50816, 45958,
       43499, 59560, 83557, 69051, 56340, 85320, 91920, 18575, 18802,
       19636, 44965, 42544, 67202, 67243, 78461, 75409, 97176, 87390,
       86868, 29416, 30613, 32753, 32904, 34762, 44240, 40807, 39371,
       44527, 11324, 59976, 68396, 86182, 48616, 48786, 46300, 48963,
       94237, 60328, 49374, 11512, 40411, 40435, 56346, 14125, 55440,
       56891, 94482,

In [111]:
Benifit_cost['IssuerId2'].unique()

array([21989, 38536, 73836, 42507, 45858, 74819, 84859, 12538, 44580,
       17540, 46944, 44785, 46211, 59809, 77233, 82285, 23307, 17100,
       17454, 18156, 51485, 30045, 33851, 52147, 53901, 58292, 60761,
       70239, 66105, 77352, 84251, 86830, 88925, 91450, 90264, 92045,
       99180, 15833, 15980, 16842, 23841, 27357, 30252, 30115, 30219,
       35783, 48121, 43274, 49193, 51398, 48129, 54172, 56503, 57451,
       77150, 59667, 85543, 86382, 97725, 98534, 99787, 45495, 28167,
       37001, 49046, 50988, 55612, 73231, 50491, 50662, 63411, 63940,
       83502, 83761, 86637, 89942, 93332, 17575, 35065, 50816, 45958,
       43499, 59560, 83557, 69051, 56340, 85320, 91920, 18575, 18802,
       19636, 44965, 42544, 67202, 67243, 78461, 75409, 97176, 87390,
       86868, 29416, 30613, 32753, 32904, 34762, 44240, 40807, 39371,
       44527, 11324, 59976, 68396, 86182, 48616, 48786, 46300, 48963,
       94237, 60328, 49374, 11512, 40411, 40435, 56346, 14125, 55440,
       56891, 94482,

In [113]:
Benifit_cost['LimitQty'].unique()

array([1.000e+03, 1.000e+00,       nan, 2.000e+00, 6.000e+01, 1.500e+03,
       1.300e+02, 4.500e+01, 1.200e+01, 3.000e+01, 1.000e+01, 3.000e+00,
       7.500e+01, 4.000e+00, 1.500e+01, 3.100e+01, 2.000e+01, 2.500e+03,
       3.600e+01, 9.000e+01, 1.000e+02, 4.200e+01, 3.500e+01, 2.600e+01,
       1.800e+02, 1.200e+02, 5.000e+01, 4.000e+01, 3.000e+03, 1.500e+02,
       8.200e+01, 6.000e+00, 5.000e+00, 1.800e+01, 4.150e+02, 1.100e+01,
       8.500e+01, 2.500e+01, 3.900e+02, 5.000e+02, 2.400e+02, 5.000e+04,
       2.000e+02, 1.250e+03, 6.000e+02, 9.000e+02, 4.000e+03, 3.750e+02,
       8.000e+01, 7.500e+04, 3.400e+01, 2.100e+02, 8.750e+02, 2.500e+02,
       3.650e+02, 1.600e+01, 1.850e+02, 1.400e+01, 3.600e+02, 9.999e+03,
       1.350e+02, 1.800e+03, 1.200e+03, 5.000e+03, 2.000e+03, 1.000e+04,
       2.200e+03, 2.340e+02, 3.000e+02, 2.400e+01, 4.800e+01, 9.000e+00,
       2.800e+01, 1.050e+02, 1.640e+02, 1.400e+02, 7.500e+02, 2.900e+01,
       7.000e+01, 8.400e+01, 1.500e+04, 1.900e+01, 

In [115]:
Benifit_cost['LimitUnit'].unique()

array(['Dollars per Year', 'Visit(s) per 6 Months', nan,
       'Visit(s) per Year', 'Days per Year', 'Dollars per Lifetime',
       'Item(s) per Year', 'Treatment(s) per Lifetime', 'Hours per Year',
       'Procedure(s) per 3 Years', 'Exam(s) per Year',
       'Treatment(s) per Benefit Period', 'Procedure(s) per Year',
       'Procedure(s) per 6 Months', 'Procedure(s) per 2 Years',
       'Procedure(s) per Lifetime', 'Days per Month',
       'Visit(s) per Benefit Period', 'Dollars per Benefit Period',
       'Item(s) per Procedure', 'Treatment(s) per Procedure',
       'Treatment(s) per 3 Years', 'Visit(s) per benefit period',
       'Procedure(s) per benefit period', 'Visit(s) per year',
       'Item(s) per year', 'Visit(s) per 6 months',
       'Treatment(s) per Year', 'Days per benefit period',
       'Exam(s) per Benefit Period', 'Procedure(s) per Benefit Period',
       'Days per Benefit Period', 'Procedure(s) per Month',
       'Item(s) per Month', 'Item(s) per Benefit Period',


In [116]:
Benifit_cost['MinimumStay'].unique()            

array([nan, 48.,  5., 90.])

In [118]:
Benifit_cost['PlanId'].unique()              

array(['21989AK0010001-00', '21989AK0010001-01', '21989AK0020001-00', ...,
       '96480WV0090003-01', '96480WV0100003-00', '96480WV0110003-00'],
      dtype=object)

In [120]:
Benifit_cost['QuantLimitOnSvc'].unique()  

array(['Yes', nan, 'No', 'yes', 'no', 'NO'], dtype=object)

In [121]:
Benifit_cost['RowNumber'].unique()                  


array([ 68, 104, 110, 111, 112, 113, 114, 115, 118, 119,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  61,  62,  63,  64,  65,  66,
        67,  69,  70,  71,  72,  73,  74,  75,  76,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       105, 106, 107, 108, 109, 116, 117, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156], dtype=int64)

In [122]:
Benifit_cost['SourceName'].unique()                  


array(['HIOS', 'OPM', 'SERFF'], dtype=object)

In [123]:
Benifit_cost['StandardComponentId'].unique()                  


array(['21989AK0010001', '21989AK0020001', '21989AK0020002', ...,
       '96480WV0090003', '96480WV0100003', '96480WV0110003'], dtype=object)

In [125]:
Benifit_cost['StateCode'].unique() 


array(['AK', 'AL', 'AZ', 'FL', 'GA', 'IN', 'LA', 'MO', 'MS', 'NC', 'ND',
       'NJ', 'OK', 'PA', 'SC', 'TN', 'TX', 'WI', 'WY', 'AR', 'DE', 'IL',
       'KS', 'ME', 'MI', 'MT', 'NH', 'NM', 'VA', 'WV', 'IA', 'ID', 'NE',
       'OH', 'SD', 'UT', 'NV', 'OR', 'HI'], dtype=object)

In [126]:
Benifit_cost['StateCode2'].unique()


array(['AK', 'AL', 'AZ', 'FL', 'GA', 'IN', 'LA', 'MO', 'MS', 'NC', 'ND',
       'NJ', 'OK', 'PA', 'SC', 'TN', 'TX', 'WI', 'WY', 'AR', 'DE', 'IL',
       'KS', 'ME', 'MI', 'MT', 'NH', 'NM', 'VA', 'WV', 'IA', 'ID', 'NE',
       'OH', 'SD', 'UT', 'NV', 'OR', 'HI'], dtype=object)

In [129]:
Benifit_cost['VersionNum'].unique()

array([ 6,  2,  3,  1,  7,  8, 10,  4,  5, 13, 12,  9, 16, 11, 14, 15, 19,
       18, 20, 17, 21, 23, 24], dtype=int64)